### ISSUE TITLE
Rimeatest 4 not working

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#258]
In Gitlab by @sainho93 on Jun 21, 2017, 17:27 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/issues/246)]

## Relevant logs, files (inifile and geometry) and/or screenshots

```python
Traceback (most recent call last):
  File "runtest_rimea_4.py", line 221, in <module>
    test.run_test(testfunction=run_rimea_test4)
  File "/Users/sainho93/Documents/Repos/jpscore/Utest/JPSRunTest.py", line 77, in run_test
    res = self.__execute_test(jpscore_exe, inifile, testfunction, *args)
  File "/Users/sainho93/Documents/Repos/jpscore/Utest/JPSRunTest.py", line 228, in __execute_test
    res = testfunction(inifile, trajfile, *args)
TypeError: run_rimea_test4() takes no arguments (2 given)

```

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Jun 13, 2018, 16:41

removed milestone
